/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as defaultLayoutRouteImport } from './app/(default)/layout'
import { Route as defaultTailorIndexRouteImport } from './app/(default)/tailor/index'
import { Route as defaultSettingsIndexRouteImport } from './app/(default)/settings/index'
import { Route as defaultDashboardIndexRouteImport } from './app/(default)/dashboard/index'
import { Route as defaultBuilderIndexRouteImport } from './app/(default)/builder/index'
import { Route as PrintResumesIdRouteImport } from './app/print/resumes/$id'
import { Route as PrintCoverLetterIdRouteImport } from './app/print/cover-letter/$id'
import { Route as defaultResumesIdRouteImport } from './app/(default)/resumes/$id'

const defaultLayoutRoute = defaultLayoutRouteImport.update({
  id: '/(default)/layout',
  path: '/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const defaultTailorIndexRoute = defaultTailorIndexRouteImport.update({
  id: '/(default)/tailor/',
  path: '/tailor/',
  getParentRoute: () => rootRouteImport,
} as any)
const defaultSettingsIndexRoute = defaultSettingsIndexRouteImport.update({
  id: '/(default)/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const defaultDashboardIndexRoute = defaultDashboardIndexRouteImport.update({
  id: '/(default)/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const defaultBuilderIndexRoute = defaultBuilderIndexRouteImport.update({
  id: '/(default)/builder/',
  path: '/builder/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintResumesIdRoute = PrintResumesIdRouteImport.update({
  id: '/print/resumes/$id',
  path: '/print/resumes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintCoverLetterIdRoute = PrintCoverLetterIdRouteImport.update({
  id: '/print/cover-letter/$id',
  path: '/print/cover-letter/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const defaultResumesIdRoute = defaultResumesIdRouteImport.update({
  id: '/(default)/resumes/$id',
  path: '/resumes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/layout': typeof defaultLayoutRoute
  '/resumes/$id': typeof defaultResumesIdRoute
  '/print/cover-letter/$id': typeof PrintCoverLetterIdRoute
  '/print/resumes/$id': typeof PrintResumesIdRoute
  '/builder/': typeof defaultBuilderIndexRoute
  '/dashboard/': typeof defaultDashboardIndexRoute
  '/settings/': typeof defaultSettingsIndexRoute
  '/tailor/': typeof defaultTailorIndexRoute
}
export interface FileRoutesByTo {
  '/layout': typeof defaultLayoutRoute
  '/resumes/$id': typeof defaultResumesIdRoute
  '/print/cover-letter/$id': typeof PrintCoverLetterIdRoute
  '/print/resumes/$id': typeof PrintResumesIdRoute
  '/builder': typeof defaultBuilderIndexRoute
  '/dashboard': typeof defaultDashboardIndexRoute
  '/settings': typeof defaultSettingsIndexRoute
  '/tailor': typeof defaultTailorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(default)/layout': typeof defaultLayoutRoute
  '/(default)/resumes/$id': typeof defaultResumesIdRoute
  '/print/cover-letter/$id': typeof PrintCoverLetterIdRoute
  '/print/resumes/$id': typeof PrintResumesIdRoute
  '/(default)/builder/': typeof defaultBuilderIndexRoute
  '/(default)/dashboard/': typeof defaultDashboardIndexRoute
  '/(default)/settings/': typeof defaultSettingsIndexRoute
  '/(default)/tailor/': typeof defaultTailorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/layout'
    | '/resumes/$id'
    | '/print/cover-letter/$id'
    | '/print/resumes/$id'
    | '/builder/'
    | '/dashboard/'
    | '/settings/'
    | '/tailor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/layout'
    | '/resumes/$id'
    | '/print/cover-letter/$id'
    | '/print/resumes/$id'
    | '/builder'
    | '/dashboard'
    | '/settings'
    | '/tailor'
  id:
    | '__root__'
    | '/(default)/layout'
    | '/(default)/resumes/$id'
    | '/print/cover-letter/$id'
    | '/print/resumes/$id'
    | '/(default)/builder/'
    | '/(default)/dashboard/'
    | '/(default)/settings/'
    | '/(default)/tailor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  defaultLayoutRoute: typeof defaultLayoutRoute
  defaultResumesIdRoute: typeof defaultResumesIdRoute
  PrintCoverLetterIdRoute: typeof PrintCoverLetterIdRoute
  PrintResumesIdRoute: typeof PrintResumesIdRoute
  defaultBuilderIndexRoute: typeof defaultBuilderIndexRoute
  defaultDashboardIndexRoute: typeof defaultDashboardIndexRoute
  defaultSettingsIndexRoute: typeof defaultSettingsIndexRoute
  defaultTailorIndexRoute: typeof defaultTailorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(default)/layout': {
      id: '/(default)/layout'
      path: '/layout'
      fullPath: '/layout'
      preLoaderRoute: typeof defaultLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(default)/tailor/': {
      id: '/(default)/tailor/'
      path: '/tailor'
      fullPath: '/tailor/'
      preLoaderRoute: typeof defaultTailorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(default)/settings/': {
      id: '/(default)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof defaultSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(default)/dashboard/': {
      id: '/(default)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof defaultDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(default)/builder/': {
      id: '/(default)/builder/'
      path: '/builder'
      fullPath: '/builder/'
      preLoaderRoute: typeof defaultBuilderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/resumes/$id': {
      id: '/print/resumes/$id'
      path: '/print/resumes/$id'
      fullPath: '/print/resumes/$id'
      preLoaderRoute: typeof PrintResumesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/cover-letter/$id': {
      id: '/print/cover-letter/$id'
      path: '/print/cover-letter/$id'
      fullPath: '/print/cover-letter/$id'
      preLoaderRoute: typeof PrintCoverLetterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(default)/resumes/$id': {
      id: '/(default)/resumes/$id'
      path: '/resumes/$id'
      fullPath: '/resumes/$id'
      preLoaderRoute: typeof defaultResumesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  defaultLayoutRoute: defaultLayoutRoute,
  defaultResumesIdRoute: defaultResumesIdRoute,
  PrintCoverLetterIdRoute: PrintCoverLetterIdRoute,
  PrintResumesIdRoute: PrintResumesIdRoute,
  defaultBuilderIndexRoute: defaultBuilderIndexRoute,
  defaultDashboardIndexRoute: defaultDashboardIndexRoute,
  defaultSettingsIndexRoute: defaultSettingsIndexRoute,
  defaultTailorIndexRoute: defaultTailorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
